version: '1'

networks:
  ktech:


volumes:
  mysql:


services:
  nginx:
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: nginx
    ports:
      - 8080:80
      - 8090:3000
    volumes:
      - ../api:/var/www/html/api
    depends_on:
      - php
      - redis
      - mysql
    networks:
      - ktech
  php:
    build:
      context: ./config/php
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: php
    volumes:
      - ../api:/var/www/html/api:delegated
    networks:
      - ktech
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 127.0.0.1:6379:6379
    networks:
      - ktech
  composer:
    build:
      context: ./config/composer
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: composer
    volumes:
      - ../api:/var/www/html/api:delegated
    working_dir: /var/www/html/api
    depends_on:
      - php
    user: laravel
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - ktech
  artisan:
    build:
      context: ./config/php
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: artisan
    volumes:
      - ../api:/var/www/html/api:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html/api
    entrypoint: [ 'php', '/var/www/html/api/artisan' ]
    networks:
      - ktech